[phases.setup]
nixPkgs = ["python313", "libgl1", "libglib2.0-0"]
aptPkgs = ["libgl1-mesa-glx", "libglib2.0-0"]

[phases.install]
cmds = ["python -m venv .venv", ".venv/Scripts/activate || . .venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "python main.py"
