spring.application.name=TeaPlanter
spring.config.import=optional:file:env.BackEnd

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Error Handling
# Security
server.error.include-message=always

# Clerk JWK Set URI
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWK_SET_URI}

# Clerk Backend API Secret Key
clerk.secret-key=${CLERK_SECRET_KEY}
