spring.application.name=TeaPlanter
server.port=${PORT:8080}
spring.config.import=optional:file:env.BackEnd

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Error Handling
# Security
server.error.include-message=always
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.type.descriptor.sql=warn
spring.mail.properties.mail.smtp.connectiontimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT:10000}
spring.mail.properties.mail.smtp.timeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT:10000}
spring.mail.properties.mail.smtp.writetimeout=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT:10000}

# Clerk JWK Set URI
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${CLERK_JWK_SET_URI}

# Clerk Backend API Secret Key
clerk.secret-key=${CLERK_SECRET_KEY}
